name: Publish

on:
  push:
    branches:
      - main

env:
  PLUGIN_NAME: kindle-import

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
      - name: install dependencies
        run: |
          npm install
      - name: test
        run: |
          npm run test
      - name: build
        run: |
          npm run build
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
