name: Publish

on:
  push:
    branches:
      - main

env:
  PLUGIN_NAME: kindle-import

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - name: install pnpm
      run: |
        npm install -g pnpm
    - name: install dependencies
      run: |
        pnpm install
    - name: build and test
      run: |
        pnpm run build
    - name: Install zip
      uses: montudor/action-zip@v1
    - name: Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}